import time
import tkinter
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import pymysql

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import mysql.connector


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/media/aa/KINGSTON/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window2 = Tk()
w0, h0 = 1920, 1080
w1, h1 = 1920, 1080

window2.geometry("1920x1080+1920+0") # <- this is the key, offset to the right by w0)
window2.configure(bg = "#FFFFFF")

window2.overrideredirect(True)


def conecta():
    
   
    try:
        conexao = pymysql.connect(
            user="butterfly@peixe",
            password="Manteigavoadora1",
            host="peixe.mariadb.database.azure.com",
            port=3306,
            database='secretariasenai'
        )
    except Exception as e:
            print(f"We can't connected with the server. \033[31m ERROR!: {e} \033[m")
    else:
       return conexao

def executaefecha(cursor, conexao):
    cursor.fetchone()
    conexao.commit()
    cursor.close()
    conexao.close()


def chamados():
    while True:
        try:
            lista = []
            conexao = conecta()
            cursor = conexao.cursor()
            cursor.execute("SELECT name, guiche FROM espera WHERE ja_atendido = 1 ORDER BY id DESC")
            linhas = cursor.fetchall()
            cont = 0
            for i in linhas:
                cont += 1
                if cont > 3: 
                    break
                lista.append(i[0])
                lista.append(i[1])
            executaefecha(cursor, conexao)
            time.sleep(2)
            chamado1.configure(text=f"{lista[0]}\nGuichê: {lista[1]}")
            chamado2.configure(text=f"{lista[2]}\nGuichê: {lista[3]}")
            chamado3.configure(text=f"{lista[4]}\nGuichê: {lista[5]}")
            chamadoprincip.configure(text=f"{linhas[0][0]}")
            chamadoguiche.configure(text=f"{linhas[0][1]}")
            chamado1.update()
            chamado2.update()
            chamado3.update()
            chamadoprincip.update()
            chamadoguiche.update()
        except:
            continue


canvas2 = Canvas(
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
canvas2.create_rectangle(
    0.0,
    1115.0,
    1115,
    0.0,
    fill="#D9D9D9",
    outline=""
)
canvas2.place(x=0, y=0)
canvas2.create_rectangle(
    0.0,
    827.0,
    1115.0,
    1080.0,
    fill="#F20505",
    outline="")
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas2.create_image(
    578.0,
    949.0,
    image=image_image_1
)

canvas2.create_text(
    1180.0,
    80.0,
    anchor="nw",
    text="ÚLTIMAS CHAMADAS",
    fill="#000000",
    font=("Gotham Bold", 60 * -1)
)

canvas2.create_text(
    400.0,
    64.0,
    anchor="nw",
    text="NOME",
    fill="#000000",
    font=("Gotham Bold", 90 * -1)
)

canvas2.create_text(
    360.0,
    420.0,
    anchor="nw",
    text="GUICHÊ",
    fill="#000000",
    font=("Gotham Bold", 90 * -1)
)

chamado1 = tkinter.Label(
    width=20,
    bg="#D9D9D9",
    font=("Gotham Medium", 52 * -1),
)
chamado1.place(
    x=1170,
    y=200
)

chamado2 = tkinter.Label(
    width=20,
    bg="#D9D9D9",
    font=("Gotham Medium", 52 * -1),
)
chamado2.place(
    x=1170,
    y=440
)

chamado3 = tkinter.Label(
    width=20,
    bg="#D9D9D9",
    font=("Gotham Medium",52 * -1),
)
chamado3.place(
    x=1170,
    y=700
)

chamadoprincip = tkinter.Label(
    width=20,
    bg="#FFFFFF",
    font=("Gotham Medium", 72 * -1),
    anchor="center",
    wraplength=1000

)

chamadoprincip.place(
    x=31.0,
    y=198.0
)

chamadoguiche = tkinter.Label(
    width=4,
    bg="#FFFFFF",
    font=("Gotham Medium", 100 * -1),
    anchor="center",

)

chamadoguiche.place(
    x=440.0,
    y=570.0
)



window2.resizable(False, False)
chamados()
window2.mainloop()


